# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
     matrix:
       go-version: ['1.19','1.20','1.21.x']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.go-version}}
        cache-dependency-path: subdir/go.sum

    - name: show the version
      run: go version
    - name: install dependencies
      run: | 
       go get .
       go get example.com/octo-examplemodule
       go get example.com/octo-examplemodule@v1.3.4
    - name: Build
      run: go build -v ./...
    - name: Test with the Go CLI
      run: go test
      
